name: SAM Validate, Build, Test, Deploy
on:
  push:
    branches: [ main, blue, green, orange, red, black, alpha ]
  workflow_call:
        
jobs:
  sam-validate-build-test-deploy:
    runs-on: self-hosted
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - name: Configure variables
        shell: bash
        id: vars
        env:
          REPO: ${{ github.repository }}
          HASH: ${{ github.sha }}
          REF: ${{ github.ref }}
        run: |
          # Set variables
          BRANCH=${REF#refs/heads/}
          REPOSITORY=`echo $REPO | tr "/" "-"`
          ENVIRONMENT=$BRANCH-$REPOSITORY
          # In this step we are setting variables and persistenting them
          # into the environment so that they can be utilized in other steps
          echo "::set-output name=branch::$BRANCH"
          echo "::set-output name=repository::$REPOSITORY"
          echo "::set-output name=environment::$ENVIRONMENT"
          # Output variables to ensure their values are set correctly when ran
          echo "The repository is $REPOSITORY"
          echo "The environment is $ENVIRONMENT"
          echo "The branch is $BRANCH"
      - name: SAM Validate
        run: |
          sam validate --config-file samconfig.toml --config-env ${{ steps.vars.outputs.branch }}
      - name: SAM Build
        run: |
          sam build --config-file samconfig.toml --config-env ${{ steps.vars.outputs.branch }}
      - name: SAM Deploy
        run: |
          # Run SAM Deploy
          sam deploy --config-file samconfig.toml --config-env ${{ steps.vars.outputs.branch }} --resolve-image-repos --no-fail-on-empty-changeset
#            --no-execute-changeset
#            --parameter-overrides \
#              'ParameterKey=Name,ParameterValue=example \
#              ParameterKey=Version,ParameterValue=${{ steps.vars.outputs.version }}'
