name: Deploy SLS Project

on:
  workflow_call:
    secrets:
      npm_token:
        required: true
  push:
    branches: [ main, blue, green, orange, red, black, alpha ]

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://govyrl.jfrog.io/govyrl/api/npm/vyrl-repo-virtual/
        scope: 'taylor@vyrl.co'
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - run: npm ci --registry https://govyrl.jfrog.io/govyrl/api/npm/vyrl-repo-virtual/
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy -s ${{ steps.extract_branch.outputs.branch }}
#       env:
#         SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
