# This is a basic workflow to help you get started with Actions

name: Single Page Application

# Controls when the workflow will run
on:
  workflow_call:
    # secrets:
    #   account_id:
    #     required: true
    #   jfrog_user:
    #     required: true
    #   jfrog_password:
    #     required: true
jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      VENV: ${{ github.ref_name }}
      API_GATEWAY_URI: ${{ secrets.API_GATEWAY_URI }}
      AWS_PRODUCTION_BUCKET_NAME: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
      AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
      CARRO_APP_ORIGIN: ${{ secrets.CARRO_APP_ORIGIN }}
      REACT_APP_BACON_SRC: ${{ secrets.REACT_APP_BACON_SRC }}
      REACT_APP_BLACKLIST_URI: ${{ secrets.REACT_APP_BLACKLIST_URI }}
      REACT_APP_FACEBOOK_APP_ID: ${{ secrets.REACT_APP_FACEBOOK_APP_ID }}
      REACT_APP_FACEBOOK_PIXEL_ID: ${{ secrets.REACT_APP_FACEBOOK_PIXEL_ID }}
      REACT_APP_FACEBOOK_SCOPE: ${{ secrets.REACT_APP_FACEBOOK_SCOPE }}
      REACT_APP_FACEBOOK_SDK_VERSION: ${{ secrets.REACT_APP_FACEBOOK_SDK_VERSION }}
      REACT_APP_GA_TRACKING_ID: ${{ secrets.REACT_APP_GA_TRACKING_ID }}
      REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
      REACT_APP_GRAPHQL_URI: ${{ secrets.REACT_APP_GRAPHQL_URI }}
      REACT_APP_INTERCOM_APP_ID: ${{ secrets.REACT_APP_INTERCOM_APP_ID }}
      REACT_APP_UPSELL_URI: ${{ secrets.REACT_APP_UPSELL_URI }}
      REACT_APP_WHAT_ENV_AM_I: ${{ secrets.REACT_APP_WHAT_ENV_AM_I }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SOURCE_DIR: "./build"
    strategy:
      matrix:
        node-version: [16.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn
        run: |
          npm i -g yarn
      - name: Yarn Install
        run: |
          yarn install
      - name: Run build
        run: yarn build-prod
      # Unit tests
      - name: Test env
        run: |
          echo "$API_GATEWAY_URI"

      - name: Run Unit Tests
        run:  yarn test
      # Upload to S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete    
      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.